[build]
builder = "DOCKERFILE"
dockerfilePath = "menu-eureka-api/Dockerfile"
buildPath = "menu-eureka-api"

[deploy]
healthcheckPath = "/"
healthcheckTimeout = 300
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 5 